//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colegio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColegioEntities : DbContext
    {
        public ColegioEntities()
            : base("name=ColegioEntities")
        {
        }
       
        //public DbSet<ProfesorSet> Profesores { get; set; }
        //public DbSet<AlumnoSet> Alumnos { get; set; }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlumnoSet> AlumnoSets { get; set; }
        public virtual DbSet<ProfesorSet> ProfesorSets { get; set; }

      
    }
}
